### PR TITLE
Show Cate's core Python dependencies

### PR DESCRIPTION
**Pull request by forman**
Renamed "About" tab in Preferences Dialog into "System". There we now also display the versions of Cate's core Python package dependencies:

image

### CODE REVIEW

**Review by dzelge — CHANGES_REQUESTED** [review]
The default api paths are not correct in config.ts. Should be **users** not **user**:

const MANAG_API_PATH = '/users/{username}/webapis';
const CLOSE_API_PATH = '/users/{username}/webapis';

**Review by TonioF — APPROVED** [review]
Works fine, love it!

**Comment by forman** [comment]
> The default api paths are not correct in config.ts. Should be **users** not **user**:
> 
> const MANAG_API_PATH = '/users/{username}/webapis';
> const CLOSE_API_PATH = '/users/{username}/webapis';

This was the previous PR.

**Comment by forman** [comment]
@dzelge fixed it.
@AliceBalfanz merging without your ok, need to move on

**Pull request merged**
